-- =====================================================================
-- 16 — Schema PostgreSQL proposto (traduzione fedele di osTicket 1.18.4)
-- ---------------------------------------------------------------------
-- Generato da setup/inc/streams/core/install-mysql.sql e VALIDATO su
-- PostgreSQL 16 (67 tabelle, 97 foreign key caricate senza errori).
--
-- Scelte:
--  * Nomi di tabelle/colonne IDENTICI all'originale (prefisso ost_) per
--    semplificare l'ETL dal database MySQL esistente.
--  * AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY (permette di
--    importare gli id originali; dopo l'import eseguire setval/ALTER ...
--    RESTART per ogni identity).
--  * ENUM -> varchar + CHECK; tinyint -> smallint (i flag bitmask restano
--    numerici); datetime/timestamp -> timestamp(0) (salvare in UTC!).
--  * Le colonne FK che in MySQL usavano 0 come "nessuno" sono qui
--    NULLABLE senza default: in ETL convertire 0 -> NULL.
--  * FK DEFERRABLE INITIALLY DEFERRED (import in qualunque ordine in una
--    transazione). Le relazioni polimorfiche (object_id/object_type,
--    thread.object_id, attachment.object_id, form_entry.object_id,
--    task.object_id, thread_referral.object_id, note.ext_id) NON hanno FK:
--    in una riscrittura "pulita" si consiglia di sostituirle con FK
--    esplicite o tabelle ponte (vedi doc 15).
--  * Non incluse: tabelle dinamiche *__cdata (sostituibili con colonna
--    jsonb + indici GIN) e _search (sostituibile con tsvector + GIN).
--  * La tabella legacy "group" è inclusa solo per compatibilità ETL.
-- =====================================================================

CREATE TABLE ost_api_key (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "isactive" smallint NOT NULL DEFAULT '1',
    "ipaddr" varchar(64) NOT NULL,
    "apikey" varchar(255) NOT NULL,
    "can_create_tickets" smallint NOT NULL DEFAULT '1',
    "can_exec_cron" smallint NOT NULL DEFAULT '1',
    "notes" text,
    "updated" timestamp(0) NOT NULL,
    "created" timestamp(0) NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("apikey")
);
CREATE INDEX ost_api_key_ipaddr_idx ON ost_api_key ("ipaddr");

CREATE TABLE ost_attachment (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "object_id" integer NOT NULL,
    "type" char(1) NOT NULL,
    "file_id" integer,
    "name" varchar(255),
    "inline" smallint NOT NULL DEFAULT '0',
    "lang" varchar(16),
    PRIMARY KEY ("id"),
    UNIQUE ("object_id", "file_id", "type"),
    UNIQUE ("file_id", "object_id")
);

CREATE TABLE ost_faq (
    "faq_id" integer GENERATED BY DEFAULT AS IDENTITY,
    "category_id" integer,
    "ispublished" smallint NOT NULL DEFAULT '0',
    "question" varchar(255) NOT NULL,
    "answer" text NOT NULL,
    "keywords" text,
    "notes" text,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("faq_id"),
    UNIQUE ("question")
);
CREATE INDEX ost_faq_category_id_idx ON ost_faq ("category_id");
CREATE INDEX ost_faq_ispublished_idx ON ost_faq ("ispublished");

CREATE TABLE ost_faq_category (
    "category_id" integer GENERATED BY DEFAULT AS IDENTITY,
    "category_pid" integer,
    "ispublic" smallint NOT NULL DEFAULT '0',
    "name" varchar(125),
    "description" text NOT NULL,
    "notes" text NOT NULL,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("category_id")
);
CREATE INDEX ost_faq_category_ispublic_idx ON ost_faq_category ("ispublic");

CREATE TABLE ost_faq_topic (
    "faq_id" integer NOT NULL,
    "topic_id" integer NOT NULL,
    PRIMARY KEY ("faq_id", "topic_id")
);

CREATE TABLE ost_sequence (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(64),
    "flags" integer,
    "next" bigint NOT NULL DEFAULT '1',
    "increment" integer DEFAULT '1',
    "padding" char(1) DEFAULT '0',
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE ost_sla (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "schedule_id" integer,
    "flags" integer NOT NULL DEFAULT 3,
    "grace_period" integer NOT NULL DEFAULT '0',
    "name" varchar(64) NOT NULL DEFAULT '',
    "notes" text,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("name")
);

CREATE TABLE ost_config (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "namespace" varchar(64) NOT NULL,
    "key" varchar(64) NOT NULL,
    "value" text NOT NULL,
    "updated" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    UNIQUE ("namespace", "key")
);

CREATE TABLE ost_form (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "pid" integer,
    "type" varchar(8) NOT NULL DEFAULT 'G',
    "flags" integer NOT NULL DEFAULT 1,
    "title" varchar(255) NOT NULL,
    "instructions" varchar(512),
    "name" varchar(64) NOT NULL DEFAULT '',
    "notes" text,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX ost_form_type_idx ON ost_form ("type");

CREATE TABLE ost_form_field (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "form_id" integer,
    "flags" integer DEFAULT 1,
    "type" varchar(255) NOT NULL DEFAULT 'text',
    "label" varchar(255) NOT NULL,
    "name" varchar(64) NOT NULL,
    "configuration" text,
    "sort" integer NOT NULL,
    "hint" varchar(512),
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX ost_form_field_form_id_idx ON ost_form_field ("form_id");
CREATE INDEX ost_form_field_sort_idx ON ost_form_field ("sort");

CREATE TABLE ost_form_entry (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "form_id" integer,
    "object_id" integer,
    "object_type" char(1) NOT NULL DEFAULT 'T',
    "sort" integer NOT NULL DEFAULT 1,
    "extra" text,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX ost_form_entry_object_type_object_id_idx ON ost_form_entry ("object_type", "object_id");

CREATE TABLE ost_form_entry_values (
    "entry_id" integer NOT NULL,
    "field_id" integer NOT NULL,
    "value" text,
    "value_id" integer,
    PRIMARY KEY ("entry_id", "field_id")
);

CREATE TABLE ost_list (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255) NOT NULL,
    "name_plural" varchar(255),
    "sort_mode" varchar(32) NOT NULL DEFAULT 'Alpha',
    "masks" integer NOT NULL DEFAULT 0,
    "type" varchar(16),
    "configuration" text NOT NULL DEFAULT '',
    "notes" text,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("id"),
    CHECK ("sort_mode" IN ('Alpha', '-Alpha', 'SortCol'))
);
CREATE INDEX ost_list_type_idx ON ost_list ("type");

CREATE TABLE ost_list_items (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "list_id" integer,
    "status" integer NOT NULL DEFAULT 1,
    "value" varchar(255) NOT NULL,
    "extra" varchar(255),
    "sort" integer NOT NULL DEFAULT 1,
    "properties" text,
    PRIMARY KEY ("id")
);
CREATE INDEX ost_list_items_list_id_idx ON ost_list_items ("list_id");

CREATE TABLE ost_department (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "pid" integer,
    "tpl_id" integer,
    "sla_id" integer,
    "schedule_id" integer,
    "email_id" integer,
    "autoresp_email_id" integer,
    "manager_id" integer,
    "flags" integer NOT NULL DEFAULT 0,
    "name" varchar(128) NOT NULL DEFAULT '',
    "signature" text NOT NULL,
    "ispublic" smallint NOT NULL DEFAULT '1',
    "group_membership" smallint NOT NULL DEFAULT '0',
    "ticket_auto_response" smallint NOT NULL DEFAULT '1',
    "message_auto_response" smallint NOT NULL DEFAULT '0',
    "path" varchar(128) NOT NULL DEFAULT '/',
    "updated" timestamp(0) NOT NULL,
    "created" timestamp(0) NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("name", "pid")
);
CREATE INDEX ost_department_manager_id_idx ON ost_department ("manager_id");
CREATE INDEX ost_department_autoresp_email_id_idx ON ost_department ("autoresp_email_id");
CREATE INDEX ost_department_tpl_id_idx ON ost_department ("tpl_id");
CREATE INDEX ost_department_flags_idx ON ost_department ("flags");

CREATE TABLE ost_draft (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "staff_id" integer NOT NULL,
    "namespace" varchar(32) NOT NULL DEFAULT '',
    "body" text NOT NULL,
    "extra" text,
    "created" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated" timestamp(0),
    PRIMARY KEY ("id")
);
CREATE INDEX ost_draft_staff_id_idx ON ost_draft ("staff_id");
CREATE INDEX ost_draft_namespace_idx ON ost_draft ("namespace");

CREATE TABLE ost_email (
    "email_id" integer GENERATED BY DEFAULT AS IDENTITY,
    "noautoresp" smallint NOT NULL DEFAULT 0,
    "priority_id" integer DEFAULT 2,
    "dept_id" integer,
    "topic_id" integer,
    "email" varchar(255) NOT NULL DEFAULT '',
    "name" varchar(255) NOT NULL DEFAULT '',
    "notes" text,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("email_id"),
    UNIQUE ("email")
);
CREATE INDEX ost_email_priority_id_idx ON ost_email ("priority_id");
CREATE INDEX ost_email_dept_id_idx ON ost_email ("dept_id");

CREATE TABLE ost_email_account (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "email_id" integer,
    "type" varchar(32) NOT NULL DEFAULT 'mailbox',
    "auth_bk" varchar(128) NOT NULL,
    "auth_id" varchar(16),
    "active" smallint NOT NULL DEFAULT 0,
    "host" varchar(128) NOT NULL DEFAULT '',
    "port" integer NOT NULL,
    "folder" varchar(255),
    "protocol" varchar(32) NOT NULL DEFAULT 'OTHER',
    "encryption" varchar(32) NOT NULL DEFAULT 'AUTO',
    "fetchfreq" smallint NOT NULL DEFAULT 5,
    "fetchmax" smallint DEFAULT 30,
    "postfetch" varchar(32) NOT NULL DEFAULT 'nothing',
    "archivefolder" varchar(255),
    "allow_spoofing" smallint DEFAULT 0,
    "num_errors" integer NOT NULL DEFAULT 0,
    "last_error_msg" text,
    "last_error" timestamp(0),
    "last_activity" timestamp(0),
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("id"),
    CHECK ("type" IN ('mailbox','smtp')),
    CHECK ("protocol" IN ('IMAP','POP','SMTP','OTHER')),
    CHECK ("encryption" IN ('NONE','AUTO','SSL')),
    CHECK ("postfetch" IN ('archive','delete','nothing'))
);
CREATE INDEX ost_email_account_email_id_idx ON ost_email_account ("email_id");
CREATE INDEX ost_email_account_type_idx ON ost_email_account ("type");

CREATE TABLE ost_filter (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "execorder" integer NOT NULL DEFAULT '99',
    "isactive" smallint NOT NULL DEFAULT '1',
    "flags" integer DEFAULT '0',
    "status" integer NOT NULL DEFAULT '0',
    "match_all_rules" smallint NOT NULL DEFAULT '0',
    "stop_onmatch" smallint NOT NULL DEFAULT '0',
    "target" varchar(32) NOT NULL DEFAULT 'Any',
    "email_id" integer,
    "name" varchar(32) NOT NULL DEFAULT '',
    "notes" text,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("id"),
    CHECK ("target" IN (  'Any',  'Web',  'Email',  'API' ))
);
CREATE INDEX ost_filter_target_idx ON ost_filter ("target");
CREATE INDEX ost_filter_email_id_idx ON ost_filter ("email_id");

CREATE TABLE ost_filter_action (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "filter_id" integer,
    "sort" integer NOT NULL DEFAULT 0,
    "type" varchar(24) NOT NULL,
    "configuration" text,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX ost_filter_action_filter_id_idx ON ost_filter_action ("filter_id");

CREATE TABLE ost_filter_rule (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "filter_id" integer,
    "what" varchar(32) NOT NULL,
    "how" varchar(32) NOT NULL,
    "val" varchar(255) NOT NULL,
    "isactive" smallint NOT NULL DEFAULT '1',
    "notes" text NOT NULL,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("filter_id", "what", "how", "val"),
    CHECK ("how" IN ('equal','not_equal','contains','dn_contain','starts','ends','match','not_match'))
);
CREATE INDEX ost_filter_rule_filter_id_idx ON ost_filter_rule ("filter_id");

CREATE TABLE ost_email_template_group (
    "tpl_id" integer GENERATED BY DEFAULT AS IDENTITY,
    "isactive" smallint NOT NULL DEFAULT '0',
    "name" varchar(32) NOT NULL DEFAULT '',
    "lang" varchar(16) NOT NULL DEFAULT 'en_US',
    "notes" text,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("tpl_id")
);

CREATE TABLE ost_email_template (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "tpl_id" integer,
    "code_name" varchar(32) NOT NULL,
    "subject" varchar(255) NOT NULL DEFAULT '',
    "body" text NOT NULL,
    "notes" text,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("tpl_id", "code_name")
);

CREATE TABLE ost_file (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ft" char(1) NOT NULL DEFAULT 'T',
    "bk" char(1) NOT NULL DEFAULT 'D',
    "type" varchar(255) NOT NULL DEFAULT '',
    "size" bigint NOT NULL DEFAULT 0,
    "key" varchar(86) NOT NULL,
    "signature" varchar(86) NOT NULL,
    "name" varchar(255) NOT NULL DEFAULT '',
    "attrs" varchar(255),
    "created" timestamp(0) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX ost_file_ft_idx ON ost_file ("ft");
CREATE INDEX ost_file_key_idx ON ost_file ("key");
CREATE INDEX ost_file_signature_idx ON ost_file ("signature");
CREATE INDEX ost_file_type_idx ON ost_file ("type");
CREATE INDEX ost_file_created_idx ON ost_file ("created");
CREATE INDEX ost_file_size_idx ON ost_file ("size");

CREATE TABLE ost_file_chunk (
    "file_id" integer NOT NULL,
    "chunk_id" integer NOT NULL,
    "filedata" bytea NOT NULL,
    PRIMARY KEY ("file_id", "chunk_id")
);

CREATE TABLE "ost_group" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "role_id" integer,
    "flags" integer NOT NULL DEFAULT '1',
    "name" varchar(120) NOT NULL DEFAULT '',
    "notes" text,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX ost_group_role_id_idx ON ost_group ("role_id");

CREATE TABLE ost_role (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "flags" integer NOT NULL DEFAULT '1',
    "name" varchar(64),
    "permissions" text,
    "notes" text,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("name")
);

CREATE TABLE ost_schedule (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "flags" integer NOT NULL DEFAULT '0',
    "name" varchar(255) NOT NULL,
    "timezone" varchar(64),
    "description" varchar(255) NOT NULL,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE ost_schedule_entry (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "schedule_id" integer,
    "flags" integer NOT NULL DEFAULT '0',
    "sort" smallint NOT NULL DEFAULT '0',
    "name" varchar(255) NOT NULL,
    "repeats" varchar(16) NOT NULL DEFAULT 'never',
    "starts_on" date,
    "starts_at" time,
    "ends_on" date,
    "ends_at" time,
    "stops_on" timestamp(0),
    "day" smallint,
    "week" smallint,
    "month" smallint,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX ost_schedule_entry_schedule_id_idx ON ost_schedule_entry ("schedule_id");
CREATE INDEX ost_schedule_entry_repeats_idx ON ost_schedule_entry ("repeats");

CREATE TABLE ost_help_topic (
    "topic_id" integer GENERATED BY DEFAULT AS IDENTITY,
    "topic_pid" integer,
    "ispublic" smallint NOT NULL DEFAULT '1',
    "noautoresp" smallint NOT NULL DEFAULT '0',
    "flags" integer DEFAULT '0',
    "status_id" integer,
    "priority_id" integer,
    "dept_id" integer,
    "staff_id" integer,
    "team_id" integer,
    "sla_id" integer,
    "page_id" integer,
    "sequence_id" integer,
    "sort" integer NOT NULL DEFAULT '0',
    "topic" varchar(128) NOT NULL DEFAULT '',
    "number_format" varchar(32),
    "notes" text,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("topic_id"),
    UNIQUE ("topic", "topic_pid")
);
CREATE INDEX ost_help_topic_topic_pid_idx ON ost_help_topic ("topic_pid");
CREATE INDEX ost_help_topic_priority_id_idx ON ost_help_topic ("priority_id");
CREATE INDEX ost_help_topic_dept_id_idx ON ost_help_topic ("dept_id");
CREATE INDEX ost_help_topic_staff_id_team_id_idx ON ost_help_topic ("staff_id", "team_id");
CREATE INDEX ost_help_topic_sla_id_idx ON ost_help_topic ("sla_id");
CREATE INDEX ost_help_topic_page_id_idx ON ost_help_topic ("page_id");

CREATE TABLE ost_help_topic_form (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "topic_id" integer,
    "form_id" integer,
    "sort" integer NOT NULL DEFAULT 1,
    "extra" text,
    PRIMARY KEY ("id")
);
CREATE INDEX ost_help_topic_form_topic_id_form_id_idx ON ost_help_topic_form ("topic_id", "form_id");

CREATE TABLE ost_organization (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(128) NOT NULL DEFAULT '',
    "manager" varchar(16) NOT NULL DEFAULT '',
    "status" integer NOT NULL DEFAULT '0',
    "domain" varchar(256) NOT NULL DEFAULT '',
    "extra" text,
    "created" timestamp(0),
    "updated" timestamp(0),
    PRIMARY KEY ("id")
);

CREATE TABLE ost_canned_response (
    "canned_id" integer GENERATED BY DEFAULT AS IDENTITY,
    "dept_id" integer,
    "isenabled" smallint NOT NULL DEFAULT '1',
    "title" varchar(255) NOT NULL DEFAULT '',
    "response" text NOT NULL,
    "lang" varchar(16) NOT NULL DEFAULT 'en_US',
    "notes" text,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("canned_id"),
    UNIQUE ("title")
);
CREATE INDEX ost_canned_response_dept_id_idx ON ost_canned_response ("dept_id");
CREATE INDEX ost_canned_response_isenabled_idx ON ost_canned_response ("isenabled");

CREATE TABLE ost_note (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "pid" integer,
    "staff_id" integer,
    "ext_id" varchar(10),
    "body" text,
    "status" integer NOT NULL DEFAULT 0,
    "sort" integer NOT NULL DEFAULT 0,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX ost_note_ext_id_idx ON ost_note ("ext_id");

CREATE TABLE ost_session (
    "session_id" varchar(255) NOT NULL DEFAULT '',
    "session_data" bytea,
    "session_expire" timestamp(0),
    "session_updated" timestamp(0),
    "user_id" varchar(16) NOT NULL DEFAULT '0',
    "user_ip" varchar(64) NOT NULL,
    "user_agent" varchar(255) NOT NULL,
    PRIMARY KEY ("session_id")
);
CREATE INDEX ost_session_session_updated_idx ON ost_session ("session_updated");
CREATE INDEX ost_session_user_id_idx ON ost_session ("user_id");

CREATE TABLE ost_staff (
    "staff_id" integer GENERATED BY DEFAULT AS IDENTITY,
    "dept_id" integer,
    "role_id" integer,
    "username" varchar(32) NOT NULL DEFAULT '',
    "firstname" varchar(32),
    "lastname" varchar(32),
    "passwd" varchar(128),
    "backend" varchar(32),
    "email" varchar(255),
    "phone" varchar(24) NOT NULL DEFAULT '',
    "phone_ext" varchar(6),
    "mobile" varchar(24) NOT NULL DEFAULT '',
    "signature" text NOT NULL,
    "lang" varchar(16),
    "timezone" varchar(64),
    "locale" varchar(16),
    "notes" text,
    "isactive" smallint NOT NULL DEFAULT '1',
    "isadmin" smallint NOT NULL DEFAULT '0',
    "isvisible" smallint NOT NULL DEFAULT '1',
    "onvacation" smallint NOT NULL DEFAULT '0',
    "assigned_only" smallint NOT NULL DEFAULT '0',
    "show_assigned_tickets" smallint NOT NULL DEFAULT '0',
    "change_passwd" smallint NOT NULL DEFAULT '0',
    "max_page_size" integer NOT NULL DEFAULT '0',
    "auto_refresh_rate" integer NOT NULL DEFAULT '0',
    "default_signature_type" varchar(32) NOT NULL DEFAULT 'none',
    "default_paper_size" varchar(32) NOT NULL DEFAULT 'Letter',
    "extra" text,
    "permissions" text,
    "created" timestamp(0) NOT NULL,
    "lastlogin" timestamp(0),
    "passwdreset" timestamp(0),
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("staff_id"),
    UNIQUE ("username"),
    CHECK ("default_signature_type" IN ( 'none', 'mine', 'dept' )),
    CHECK ("default_paper_size" IN ( 'Letter', 'Legal', 'Ledger', 'A4', 'A3' ))
);
CREATE INDEX ost_staff_dept_id_idx ON ost_staff ("dept_id");
CREATE INDEX ost_staff_isadmin_idx ON ost_staff ("isadmin");
CREATE INDEX ost_staff_isactive_idx ON ost_staff ("isactive");
CREATE INDEX ost_staff_onvacation_idx ON ost_staff ("onvacation");

CREATE TABLE ost_staff_dept_access (
    "staff_id" integer NOT NULL DEFAULT '0',
    "dept_id" integer NOT NULL DEFAULT '0',
    "role_id" integer,
    "flags" integer NOT NULL DEFAULT '1',
    PRIMARY KEY ("staff_id", "dept_id")
);
CREATE INDEX ost_staff_dept_access_dept_id_idx ON ost_staff_dept_access ("dept_id");

CREATE TABLE ost_syslog (
    "log_id" integer GENERATED BY DEFAULT AS IDENTITY,
    "log_type" varchar(32) NOT NULL,
    "title" varchar(255) NOT NULL,
    "log" text NOT NULL,
    "logger" varchar(64) NOT NULL,
    "ip_address" varchar(64) NOT NULL,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("log_id"),
    CHECK ("log_type" IN ('Debug','Warning','Error'))
);
CREATE INDEX ost_syslog_log_type_idx ON ost_syslog ("log_type");

CREATE TABLE ost_team (
    "team_id" integer GENERATED BY DEFAULT AS IDENTITY,
    "lead_id" integer,
    "flags" integer NOT NULL DEFAULT 1,
    "name" varchar(125) NOT NULL DEFAULT '',
    "notes" text,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("team_id"),
    UNIQUE ("name")
);
CREATE INDEX ost_team_lead_id_idx ON ost_team ("lead_id");

CREATE TABLE ost_team_member (
    "team_id" integer NOT NULL DEFAULT '0',
    "staff_id" integer NOT NULL,
    "flags" integer NOT NULL DEFAULT '0',
    PRIMARY KEY ("team_id", "staff_id")
);
CREATE INDEX ost_team_member_staff_id_idx ON ost_team_member ("staff_id");

CREATE TABLE ost_thread (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "object_id" integer NOT NULL,
    "object_type" char(1) NOT NULL,
    "extra" text,
    "lastresponse" timestamp(0),
    "lastmessage" timestamp(0),
    "created" timestamp(0) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX ost_thread_object_id_idx ON ost_thread ("object_id");
CREATE INDEX ost_thread_object_type_idx ON ost_thread ("object_type");

CREATE TABLE ost_thread_entry (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "pid" integer,
    "thread_id" integer,
    "staff_id" integer,
    "user_id" integer,
    "type" char(1) NOT NULL DEFAULT '',
    "flags" integer NOT NULL DEFAULT '0',
    "poster" varchar(128) NOT NULL DEFAULT '',
    "editor" integer,
    "editor_type" char(1),
    "source" varchar(32) NOT NULL DEFAULT '',
    "title" varchar(255),
    "body" text NOT NULL,
    "format" varchar(16) NOT NULL DEFAULT 'html',
    "ip_address" varchar(64) NOT NULL DEFAULT '',
    "extra" text,
    "recipients" text,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX ost_thread_entry_pid_idx ON ost_thread_entry ("pid");
CREATE INDEX ost_thread_entry_thread_id_idx ON ost_thread_entry ("thread_id");
CREATE INDEX ost_thread_entry_staff_id_idx ON ost_thread_entry ("staff_id");
CREATE INDEX ost_thread_entry_type_idx ON ost_thread_entry ("type");

CREATE TABLE ost_thread_entry_email (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "thread_entry_id" integer,
    "email_id" integer,
    "mid" varchar(255) NOT NULL,
    "headers" text,
    PRIMARY KEY ("id")
);
CREATE INDEX ost_thread_entry_email_thread_entry_id_idx ON ost_thread_entry_email ("thread_entry_id");
CREATE INDEX ost_thread_entry_email_mid_idx ON ost_thread_entry_email ("mid");
CREATE INDEX ost_thread_entry_email_email_id_idx ON ost_thread_entry_email ("email_id");

CREATE TABLE ost_thread_entry_merge (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "thread_entry_id" integer,
    "data" text,
    PRIMARY KEY ("id")
);
CREATE INDEX ost_thread_entry_merge_thread_entry_id_idx ON ost_thread_entry_merge ("thread_entry_id");

CREATE TABLE ost_ticket (
    "ticket_id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ticket_pid" integer,
    "number" varchar(20),
    "user_id" integer,
    "user_email_id" integer,
    "status_id" integer,
    "dept_id" integer,
    "sla_id" integer,
    "topic_id" integer,
    "staff_id" integer,
    "team_id" integer,
    "email_id" integer,
    "lock_id" integer,
    "flags" integer NOT NULL DEFAULT '0',
    "sort" integer NOT NULL DEFAULT '0',
    "ip_address" varchar(64) NOT NULL DEFAULT '',
    "source" varchar(32) NOT NULL DEFAULT 'Other',
    "source_extra" varchar(40),
    "isoverdue" smallint NOT NULL DEFAULT '0',
    "isanswered" smallint NOT NULL DEFAULT '0',
    "duedate" timestamp(0),
    "est_duedate" timestamp(0),
    "reopened" timestamp(0),
    "closed" timestamp(0),
    "lastupdate" timestamp(0),
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("ticket_id"),
    CHECK ("source" IN ('Web','Email','Phone','API','Other'))
);
CREATE INDEX ost_ticket_user_id_idx ON ost_ticket ("user_id");
CREATE INDEX ost_ticket_dept_id_idx ON ost_ticket ("dept_id");
CREATE INDEX ost_ticket_staff_id_idx ON ost_ticket ("staff_id");
CREATE INDEX ost_ticket_team_id_idx ON ost_ticket ("team_id");
CREATE INDEX ost_ticket_status_id_idx ON ost_ticket ("status_id");
CREATE INDEX ost_ticket_created_idx ON ost_ticket ("created");
CREATE INDEX ost_ticket_closed_idx ON ost_ticket ("closed");
CREATE INDEX ost_ticket_duedate_idx ON ost_ticket ("duedate");
CREATE INDEX ost_ticket_topic_id_idx ON ost_ticket ("topic_id");
CREATE INDEX ost_ticket_sla_id_idx ON ost_ticket ("sla_id");
CREATE INDEX ost_ticket_ticket_pid_idx ON ost_ticket ("ticket_pid");

CREATE TABLE ost_lock (
    "lock_id" integer GENERATED BY DEFAULT AS IDENTITY,
    "staff_id" integer,
    "expire" timestamp(0),
    "code" varchar(20),
    "created" timestamp(0) NOT NULL,
    PRIMARY KEY ("lock_id")
);
CREATE INDEX ost_lock_staff_id_idx ON ost_lock ("staff_id");

CREATE TABLE ost_event (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(60) NOT NULL,
    "description" varchar(60),
    PRIMARY KEY ("id"),
    UNIQUE ("name")
);

CREATE TABLE ost_thread_event (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "thread_id" integer,
    "thread_type" char(1) NOT NULL DEFAULT '',
    "event_id" integer,
    "staff_id" integer,
    "team_id" integer,
    "dept_id" integer,
    "topic_id" integer,
    "data" varchar(1024),
    "username" varchar(128) NOT NULL DEFAULT 'SYSTEM',
    "uid" integer,
    "uid_type" char(1) NOT NULL DEFAULT 'S',
    "annulled" smallint NOT NULL DEFAULT '0',
    "timestamp" timestamp(0) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX ost_thread_event_thread_id_event_id_timestamp_idx ON ost_thread_event ("thread_id", "event_id", "timestamp");
CREATE INDEX ost_thread_event_timestamp_event_id_idx ON ost_thread_event ("timestamp", "event_id");

CREATE TABLE ost_thread_referral (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "thread_id" integer,
    "object_id" integer NOT NULL,
    "object_type" char(1) NOT NULL,
    "created" timestamp(0) NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("object_id", "object_type", "thread_id")
);
CREATE INDEX ost_thread_referral_thread_id_idx ON ost_thread_referral ("thread_id");

CREATE TABLE ost_ticket_status (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(60) NOT NULL DEFAULT '',
    "state" varchar(16),
    "mode" integer NOT NULL DEFAULT '0',
    "flags" integer NOT NULL DEFAULT '0',
    "sort" integer NOT NULL DEFAULT '0',
    "properties" text NOT NULL,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("name")
);
CREATE INDEX ost_ticket_status_state_idx ON ost_ticket_status ("state");

CREATE TABLE ost_ticket_priority (
    "priority_id" integer GENERATED BY DEFAULT AS IDENTITY,
    "priority" varchar(60) NOT NULL DEFAULT '',
    "priority_desc" varchar(30) NOT NULL DEFAULT '',
    "priority_color" varchar(7) NOT NULL DEFAULT '',
    "priority_urgency" smallint NOT NULL DEFAULT '0',
    "ispublic" smallint NOT NULL DEFAULT '1',
    PRIMARY KEY ("priority_id"),
    UNIQUE ("priority")
);
CREATE INDEX ost_ticket_priority_priority_urgency_idx ON ost_ticket_priority ("priority_urgency");
CREATE INDEX ost_ticket_priority_ispublic_idx ON ost_ticket_priority ("ispublic");

CREATE TABLE ost_thread_collaborator (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "flags" integer NOT NULL DEFAULT '1',
    "thread_id" integer,
    "user_id" integer,
    "role" char(1) NOT NULL DEFAULT 'M',
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("thread_id", "user_id")
);
CREATE INDEX ost_thread_collaborator_user_id_idx ON ost_thread_collaborator ("user_id");

CREATE TABLE ost_task (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "object_id" integer NOT NULL DEFAULT '0',
    "object_type" char(1) NOT NULL,
    "number" varchar(20),
    "dept_id" integer,
    "staff_id" integer,
    "team_id" integer,
    "lock_id" integer,
    "flags" integer NOT NULL DEFAULT '0',
    "duedate" timestamp(0),
    "closed" timestamp(0),
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX ost_task_dept_id_idx ON ost_task ("dept_id");
CREATE INDEX ost_task_staff_id_idx ON ost_task ("staff_id");
CREATE INDEX ost_task_team_id_idx ON ost_task ("team_id");
CREATE INDEX ost_task_created_idx ON ost_task ("created");
CREATE INDEX ost_task_object_id_object_type_idx ON ost_task ("object_id", "object_type");
CREATE INDEX ost_task_flags_idx ON ost_task ("flags");

CREATE TABLE ost_content (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "isactive" smallint NOT NULL DEFAULT '0',
    "type" varchar(32) NOT NULL DEFAULT 'other',
    "name" varchar(255) NOT NULL,
    "body" text NOT NULL,
    "notes" text,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("name")
);

CREATE TABLE ost_plugin (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255) NOT NULL,
    "install_path" varchar(60) NOT NULL,
    "isphar" smallint NOT NULL DEFAULT 0,
    "isactive" smallint NOT NULL DEFAULT 0,
    "version" varchar(64),
    "notes" text,
    "installed" timestamp(0) NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("install_path")
);

CREATE TABLE ost_plugin_instance (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "plugin_id" integer,
    "flags" integer NOT NULL DEFAULT 0,
    "name" varchar(255) NOT NULL DEFAULT '',
    "notes" text,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0),
    PRIMARY KEY ("id")
);
CREATE INDEX ost_plugin_instance_plugin_id_idx ON ost_plugin_instance ("plugin_id");

CREATE TABLE ost_queue (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "parent_id" integer,
    "columns_id" integer,
    "sort_id" integer,
    "flags" integer NOT NULL DEFAULT 0,
    "staff_id" integer,
    "sort" integer NOT NULL DEFAULT 0,
    "title" varchar(60),
    "config" text,
    "filter" varchar(64),
    "root" varchar(32),
    "path" varchar(80) NOT NULL DEFAULT '/',
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX ost_queue_staff_id_idx ON ost_queue ("staff_id");
CREATE INDEX ost_queue_parent_id_idx ON ost_queue ("parent_id");

CREATE TABLE ost_queue_column (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "flags" integer NOT NULL DEFAULT '0',
    "name" varchar(64) NOT NULL DEFAULT '',
    "primary" varchar(64) NOT NULL DEFAULT '',
    "secondary" varchar(64),
    "filter" varchar(32),
    "truncate" varchar(16),
    "annotations" text,
    "conditions" text,
    "extra" text,
    PRIMARY KEY ("id")
);

CREATE TABLE ost_queue_columns (
    "queue_id" integer NOT NULL,
    "column_id" integer NOT NULL,
    "staff_id" integer NOT NULL,
    "bits" integer NOT NULL DEFAULT '0',
    "sort" integer NOT NULL DEFAULT '1',
    "heading" varchar(64),
    "width" integer NOT NULL DEFAULT '100',
    PRIMARY KEY ("queue_id", "column_id", "staff_id")
);

CREATE TABLE ost_queue_sort (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "root" varchar(32),
    "name" varchar(64) NOT NULL DEFAULT '',
    "columns" text,
    "updated" timestamp(0),
    PRIMARY KEY ("id")
);

CREATE TABLE ost_queue_sorts (
    "queue_id" integer NOT NULL,
    "sort_id" integer NOT NULL,
    "bits" integer NOT NULL DEFAULT '0',
    "sort" integer NOT NULL DEFAULT '0',
    PRIMARY KEY ("queue_id", "sort_id")
);

CREATE TABLE ost_queue_export (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "queue_id" integer,
    "path" varchar(64) NOT NULL DEFAULT '',
    "heading" varchar(64),
    "sort" integer NOT NULL DEFAULT '1',
    PRIMARY KEY ("id")
);
CREATE INDEX ost_queue_export_queue_id_idx ON ost_queue_export ("queue_id");

CREATE TABLE ost_queue_config (
    "queue_id" integer NOT NULL,
    "staff_id" integer NOT NULL,
    "setting" text,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("queue_id", "staff_id")
);

CREATE TABLE ost_translation (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "object_hash" char(16),
    "type" varchar(32),
    "flags" integer NOT NULL DEFAULT '0',
    "revision" integer,
    "agent_id" integer NOT NULL DEFAULT '0',
    "lang" varchar(16) NOT NULL DEFAULT '',
    "text" text NOT NULL,
    "source_text" text,
    "updated" timestamp(0),
    PRIMARY KEY ("id"),
    CHECK ("type" IN ('phrase','article','override'))
);
CREATE INDEX ost_translation_type_lang_idx ON ost_translation ("type", "lang");
CREATE INDEX ost_translation_object_hash_idx ON ost_translation ("object_hash");

CREATE TABLE ost_user (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "org_id" integer,
    "default_email_id" integer,
    "status" integer NOT NULL DEFAULT '0',
    "name" varchar(128) NOT NULL,
    "created" timestamp(0) NOT NULL,
    "updated" timestamp(0) NOT NULL,
    PRIMARY KEY ("id")
);
CREATE INDEX ost_user_org_id_idx ON ost_user ("org_id");
CREATE INDEX ost_user_default_email_id_idx ON ost_user ("default_email_id");
CREATE INDEX ost_user_name_idx ON ost_user ("name");

CREATE TABLE ost_user_email (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "user_id" integer,
    "flags" integer NOT NULL DEFAULT 0,
    "address" varchar(255) NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("address")
);
CREATE INDEX ost_user_email_user_id_idx ON ost_user_email ("user_id");

CREATE TABLE ost_user_account (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "user_id" integer,
    "status" integer NOT NULL DEFAULT '0',
    "timezone" varchar(64),
    "lang" varchar(16),
    "username" varchar(64),
    "passwd" varchar(128),
    "backend" varchar(32),
    "extra" text,
    "registered" timestamp(0) DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    UNIQUE ("username")
);
CREATE INDEX ost_user_account_user_id_idx ON ost_user_account ("user_id");


-- Foreign keys (0 => NULL must be converted during data migration)
ALTER TABLE ost_attachment ADD CONSTRAINT fk_attachment_file_id FOREIGN KEY ("file_id") REFERENCES ost_file ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_faq ADD CONSTRAINT fk_faq_category_id FOREIGN KEY ("category_id") REFERENCES ost_faq_category ("category_id") ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_faq_category ADD CONSTRAINT fk_faq_category_category_pid FOREIGN KEY ("category_pid") REFERENCES ost_faq_category ("category_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_faq_topic ADD CONSTRAINT fk_faq_topic_faq_id FOREIGN KEY ("faq_id") REFERENCES ost_faq ("faq_id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_faq_topic ADD CONSTRAINT fk_faq_topic_topic_id FOREIGN KEY ("topic_id") REFERENCES ost_help_topic ("topic_id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_sla ADD CONSTRAINT fk_sla_schedule_id FOREIGN KEY ("schedule_id") REFERENCES ost_schedule ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_form_field ADD CONSTRAINT fk_form_field_form_id FOREIGN KEY ("form_id") REFERENCES ost_form ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_form_entry ADD CONSTRAINT fk_form_entry_form_id FOREIGN KEY ("form_id") REFERENCES ost_form ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_form_entry_values ADD CONSTRAINT fk_form_entry_values_entry_id FOREIGN KEY ("entry_id") REFERENCES ost_form_entry ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_form_entry_values ADD CONSTRAINT fk_form_entry_values_field_id FOREIGN KEY ("field_id") REFERENCES ost_form_field ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_list_items ADD CONSTRAINT fk_list_items_list_id FOREIGN KEY ("list_id") REFERENCES ost_list ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_department ADD CONSTRAINT fk_department_pid FOREIGN KEY ("pid") REFERENCES ost_department ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_department ADD CONSTRAINT fk_department_tpl_id FOREIGN KEY ("tpl_id") REFERENCES ost_email_template_group ("tpl_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_department ADD CONSTRAINT fk_department_sla_id FOREIGN KEY ("sla_id") REFERENCES ost_sla ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_department ADD CONSTRAINT fk_department_schedule_id FOREIGN KEY ("schedule_id") REFERENCES ost_schedule ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_department ADD CONSTRAINT fk_department_email_id FOREIGN KEY ("email_id") REFERENCES ost_email ("email_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_department ADD CONSTRAINT fk_department_autoresp_email_id FOREIGN KEY ("autoresp_email_id") REFERENCES ost_email ("email_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_department ADD CONSTRAINT fk_department_manager_id FOREIGN KEY ("manager_id") REFERENCES ost_staff ("staff_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_email ADD CONSTRAINT fk_email_priority_id FOREIGN KEY ("priority_id") REFERENCES ost_ticket_priority ("priority_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_email ADD CONSTRAINT fk_email_dept_id FOREIGN KEY ("dept_id") REFERENCES ost_department ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_email ADD CONSTRAINT fk_email_topic_id FOREIGN KEY ("topic_id") REFERENCES ost_help_topic ("topic_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_email_account ADD CONSTRAINT fk_email_account_email_id FOREIGN KEY ("email_id") REFERENCES ost_email ("email_id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_filter ADD CONSTRAINT fk_filter_email_id FOREIGN KEY ("email_id") REFERENCES ost_email ("email_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_filter_action ADD CONSTRAINT fk_filter_action_filter_id FOREIGN KEY ("filter_id") REFERENCES ost_filter ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_filter_rule ADD CONSTRAINT fk_filter_rule_filter_id FOREIGN KEY ("filter_id") REFERENCES ost_filter ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_email_template ADD CONSTRAINT fk_email_template_tpl_id FOREIGN KEY ("tpl_id") REFERENCES ost_email_template_group ("tpl_id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_file_chunk ADD CONSTRAINT fk_file_chunk_file_id FOREIGN KEY ("file_id") REFERENCES ost_file ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "ost_group" ADD CONSTRAINT fk_group_role_id FOREIGN KEY ("role_id") REFERENCES ost_role ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_schedule_entry ADD CONSTRAINT fk_schedule_entry_schedule_id FOREIGN KEY ("schedule_id") REFERENCES ost_schedule ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_help_topic ADD CONSTRAINT fk_help_topic_topic_pid FOREIGN KEY ("topic_pid") REFERENCES ost_help_topic ("topic_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_help_topic ADD CONSTRAINT fk_help_topic_status_id FOREIGN KEY ("status_id") REFERENCES ost_ticket_status ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_help_topic ADD CONSTRAINT fk_help_topic_priority_id FOREIGN KEY ("priority_id") REFERENCES ost_ticket_priority ("priority_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_help_topic ADD CONSTRAINT fk_help_topic_dept_id FOREIGN KEY ("dept_id") REFERENCES ost_department ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_help_topic ADD CONSTRAINT fk_help_topic_staff_id FOREIGN KEY ("staff_id") REFERENCES ost_staff ("staff_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_help_topic ADD CONSTRAINT fk_help_topic_team_id FOREIGN KEY ("team_id") REFERENCES ost_team ("team_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_help_topic ADD CONSTRAINT fk_help_topic_sla_id FOREIGN KEY ("sla_id") REFERENCES ost_sla ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_help_topic ADD CONSTRAINT fk_help_topic_page_id FOREIGN KEY ("page_id") REFERENCES ost_content ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_help_topic ADD CONSTRAINT fk_help_topic_sequence_id FOREIGN KEY ("sequence_id") REFERENCES ost_sequence ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_help_topic_form ADD CONSTRAINT fk_help_topic_form_topic_id FOREIGN KEY ("topic_id") REFERENCES ost_help_topic ("topic_id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_help_topic_form ADD CONSTRAINT fk_help_topic_form_form_id FOREIGN KEY ("form_id") REFERENCES ost_form ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_canned_response ADD CONSTRAINT fk_canned_response_dept_id FOREIGN KEY ("dept_id") REFERENCES ost_department ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_note ADD CONSTRAINT fk_note_staff_id FOREIGN KEY ("staff_id") REFERENCES ost_staff ("staff_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_staff ADD CONSTRAINT fk_staff_dept_id FOREIGN KEY ("dept_id") REFERENCES ost_department ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_staff ADD CONSTRAINT fk_staff_role_id FOREIGN KEY ("role_id") REFERENCES ost_role ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_staff_dept_access ADD CONSTRAINT fk_staff_dept_access_staff_id FOREIGN KEY ("staff_id") REFERENCES ost_staff ("staff_id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_staff_dept_access ADD CONSTRAINT fk_staff_dept_access_dept_id FOREIGN KEY ("dept_id") REFERENCES ost_department ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_staff_dept_access ADD CONSTRAINT fk_staff_dept_access_role_id FOREIGN KEY ("role_id") REFERENCES ost_role ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_team ADD CONSTRAINT fk_team_lead_id FOREIGN KEY ("lead_id") REFERENCES ost_staff ("staff_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_team_member ADD CONSTRAINT fk_team_member_team_id FOREIGN KEY ("team_id") REFERENCES ost_team ("team_id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_team_member ADD CONSTRAINT fk_team_member_staff_id FOREIGN KEY ("staff_id") REFERENCES ost_staff ("staff_id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_thread_entry ADD CONSTRAINT fk_thread_entry_thread_id FOREIGN KEY ("thread_id") REFERENCES ost_thread ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_thread_entry ADD CONSTRAINT fk_thread_entry_pid FOREIGN KEY ("pid") REFERENCES ost_thread_entry ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_thread_entry ADD CONSTRAINT fk_thread_entry_staff_id FOREIGN KEY ("staff_id") REFERENCES ost_staff ("staff_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_thread_entry ADD CONSTRAINT fk_thread_entry_user_id FOREIGN KEY ("user_id") REFERENCES ost_user ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_thread_entry_email ADD CONSTRAINT fk_thread_entry_email_thread_entry_id FOREIGN KEY ("thread_entry_id") REFERENCES ost_thread_entry ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_thread_entry_email ADD CONSTRAINT fk_thread_entry_email_email_id FOREIGN KEY ("email_id") REFERENCES ost_email ("email_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_thread_entry_merge ADD CONSTRAINT fk_thread_entry_merge_thread_entry_id FOREIGN KEY ("thread_entry_id") REFERENCES ost_thread_entry ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_ticket ADD CONSTRAINT fk_ticket_ticket_pid FOREIGN KEY ("ticket_pid") REFERENCES ost_ticket ("ticket_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_ticket ADD CONSTRAINT fk_ticket_user_id FOREIGN KEY ("user_id") REFERENCES ost_user ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_ticket ADD CONSTRAINT fk_ticket_user_email_id FOREIGN KEY ("user_email_id") REFERENCES ost_user_email ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_ticket ADD CONSTRAINT fk_ticket_status_id FOREIGN KEY ("status_id") REFERENCES ost_ticket_status ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_ticket ADD CONSTRAINT fk_ticket_dept_id FOREIGN KEY ("dept_id") REFERENCES ost_department ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_ticket ADD CONSTRAINT fk_ticket_sla_id FOREIGN KEY ("sla_id") REFERENCES ost_sla ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_ticket ADD CONSTRAINT fk_ticket_topic_id FOREIGN KEY ("topic_id") REFERENCES ost_help_topic ("topic_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_ticket ADD CONSTRAINT fk_ticket_staff_id FOREIGN KEY ("staff_id") REFERENCES ost_staff ("staff_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_ticket ADD CONSTRAINT fk_ticket_team_id FOREIGN KEY ("team_id") REFERENCES ost_team ("team_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_ticket ADD CONSTRAINT fk_ticket_email_id FOREIGN KEY ("email_id") REFERENCES ost_email ("email_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_ticket ADD CONSTRAINT fk_ticket_lock_id FOREIGN KEY ("lock_id") REFERENCES ost_lock ("lock_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_lock ADD CONSTRAINT fk_lock_staff_id FOREIGN KEY ("staff_id") REFERENCES ost_staff ("staff_id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_thread_event ADD CONSTRAINT fk_thread_event_thread_id FOREIGN KEY ("thread_id") REFERENCES ost_thread ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_thread_event ADD CONSTRAINT fk_thread_event_event_id FOREIGN KEY ("event_id") REFERENCES ost_event ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_thread_event ADD CONSTRAINT fk_thread_event_staff_id FOREIGN KEY ("staff_id") REFERENCES ost_staff ("staff_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_thread_event ADD CONSTRAINT fk_thread_event_team_id FOREIGN KEY ("team_id") REFERENCES ost_team ("team_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_thread_event ADD CONSTRAINT fk_thread_event_dept_id FOREIGN KEY ("dept_id") REFERENCES ost_department ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_thread_event ADD CONSTRAINT fk_thread_event_topic_id FOREIGN KEY ("topic_id") REFERENCES ost_help_topic ("topic_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_thread_referral ADD CONSTRAINT fk_thread_referral_thread_id FOREIGN KEY ("thread_id") REFERENCES ost_thread ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_thread_collaborator ADD CONSTRAINT fk_thread_collaborator_thread_id FOREIGN KEY ("thread_id") REFERENCES ost_thread ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_thread_collaborator ADD CONSTRAINT fk_thread_collaborator_user_id FOREIGN KEY ("user_id") REFERENCES ost_user ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_task ADD CONSTRAINT fk_task_dept_id FOREIGN KEY ("dept_id") REFERENCES ost_department ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_task ADD CONSTRAINT fk_task_staff_id FOREIGN KEY ("staff_id") REFERENCES ost_staff ("staff_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_task ADD CONSTRAINT fk_task_team_id FOREIGN KEY ("team_id") REFERENCES ost_team ("team_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_task ADD CONSTRAINT fk_task_lock_id FOREIGN KEY ("lock_id") REFERENCES ost_lock ("lock_id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_plugin_instance ADD CONSTRAINT fk_plugin_instance_plugin_id FOREIGN KEY ("plugin_id") REFERENCES ost_plugin ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_queue ADD CONSTRAINT fk_queue_parent_id FOREIGN KEY ("parent_id") REFERENCES ost_queue ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_queue ADD CONSTRAINT fk_queue_sort_id FOREIGN KEY ("sort_id") REFERENCES ost_queue_sort ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_queue ADD CONSTRAINT fk_queue_staff_id FOREIGN KEY ("staff_id") REFERENCES ost_staff ("staff_id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_queue_columns ADD CONSTRAINT fk_queue_columns_queue_id FOREIGN KEY ("queue_id") REFERENCES ost_queue ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_queue_columns ADD CONSTRAINT fk_queue_columns_column_id FOREIGN KEY ("column_id") REFERENCES ost_queue_column ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_queue_sorts ADD CONSTRAINT fk_queue_sorts_queue_id FOREIGN KEY ("queue_id") REFERENCES ost_queue ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_queue_sorts ADD CONSTRAINT fk_queue_sorts_sort_id FOREIGN KEY ("sort_id") REFERENCES ost_queue_sort ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_queue_export ADD CONSTRAINT fk_queue_export_queue_id FOREIGN KEY ("queue_id") REFERENCES ost_queue ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_queue_config ADD CONSTRAINT fk_queue_config_queue_id FOREIGN KEY ("queue_id") REFERENCES ost_queue ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_queue_config ADD CONSTRAINT fk_queue_config_staff_id FOREIGN KEY ("staff_id") REFERENCES ost_staff ("staff_id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_user ADD CONSTRAINT fk_user_org_id FOREIGN KEY ("org_id") REFERENCES ost_organization ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_user ADD CONSTRAINT fk_user_default_email_id FOREIGN KEY ("default_email_id") REFERENCES ost_user_email ("id") ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_user_email ADD CONSTRAINT fk_user_email_user_id FOREIGN KEY ("user_id") REFERENCES ost_user ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ost_user_account ADD CONSTRAINT fk_user_account_user_id FOREIGN KEY ("user_id") REFERENCES ost_user ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
