#!/usr/bin/env node
// Genera src/server/db/schema.gen.ts introspezionando il DB osTicket.
// - toglie il prefisso tabelle (OST_TABLE_PREFIX, default "ost_") dai nomi nel tipo DB:
//   il prefisso viene aggiunto a runtime da TablePrefixPlugin;
// - i datetime restano stringhe "YYYY-MM-DD HH:MM:SS" nel fuso del DB (mysql2 dateStrings),
//   come li tratta il PHP (doc 01 §12).
// Uso: DATABASE_URL=mysql://user:pass@host/db node scripts/db-codegen.mjs
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const prefix = process.env.OST_TABLE_PREFIX ?? "ost_";
const url = process.env.DATABASE_URL;
if (!url) {
  console.error("DATABASE_URL mancante");
  process.exit(1);
}

const tmp = join(mkdtempSync(join(tmpdir(), "codegen-")), "schema.ts");
execFileSync(
  "npx",
  ["kysely-codegen", "--dialect", "mysql", "--out-file", tmp, "--include-pattern", `${prefix}*`],
  { stdio: "inherit", env: { ...process.env, DATABASE_URL: url } },
);

const pascal = (s) =>
  s
    .split("_")
    .filter(Boolean)
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join("");

let src = readFileSync(tmp, "utf8");
const tables = [...src.matchAll(new RegExp(`^  (${prefix}\\w+): (\\w+);$`, "gm"))].map((m) => ({
  table: m[1],
  iface: m[2],
}));

for (const { table, iface } of tables) {
  const bare = table.slice(prefix.length);
  const newIface = `${pascal(bare)}Table`;
  src = src.replace(new RegExp(`\\b${iface}\\b`, "g"), newIface);
  src = src.replace(`  ${table}: ${newIface};`, `  ${bare}: ${newIface};`);
}

// DATETIME/DATE/TIMESTAMP → stringa nel fuso del DB
src = src.replace(/\bDate\b/g, "DbDateTime");
src = src.replace(
  'import type { ColumnType } from "kysely";',
  'import type { ColumnType } from "kysely";\n\n/** Datetime MySQL "YYYY-MM-DD HH:MM:SS" nel fuso del server DB (config core.db_timezone). */\nexport type DbDateTime = string;',
);
src = src.replace(
  "This file was generated by kysely-codegen.",
  "This file was generated by kysely-codegen (scripts/db-codegen.mjs).",
);

const names = tables.map((t) => JSON.stringify(t.table.slice(prefix.length))).join(",\n  ");
src += `\n/** Nomi (senza prefisso) di tutte le tabelle osTicket. */\nexport const OST_TABLES = [\n  ${names},\n] as const;\n`;

writeFileSync("src/server/db/schema.gen.ts", src);
console.log(`schema.gen.ts: ${tables.length} tabelle (prefisso "${prefix}" rimosso)`);
